name: quran_app_2025
description: "A beautiful Quran app with complete features"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.4.0
  http: ^1.5.0
  just_audio: ^0.10.5
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  url_launcher: ^6.1.11
  share_plus: ^7.0.1
  flutter_dotenv: ^5.0.2
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4 # Downgraded to compatible version

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  adaptive_icon_background: "#2E7D32"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#2E7D32"

flutter_native_splash:
  color: "#2E7D32"
  image: assets/icons/splash_icon.png
  branding: assets/icons/branding.png
  branding_mode: bottom
  branding_bottom_padding: 24
  color_dark: "#1B5E20"
  image_dark: assets/icons/splash_icon.png
  branding_dark: assets/icons/branding.png
  android_12:
    image: assets/icons/splash_icon.png
    color: "#2E7D32"
    icon_background_color: "#2E7D32"
    image_dark: assets/icons/splash_icon.png
    color_dark: "#1B5E20"
    icon_background_color_dark: "#1B5E20"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Amiri
  #     fonts:
  #       - asset: assets/fonts/Amiri-Regular.ttf
  #       - asset: assets/fonts/Amiri-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Amiri-Italic.ttf
  #         style: italic
  #   - family: ScheherazadeNew
  #     fonts:
  #       - asset: assets/fonts/ScheherazadeNew-Regular.ttf
  #       - asset: assets/fonts/ScheherazadeNew-Bold.ttf
  #         weight: 700
